# Generated by Django 5.2.7 on 2025-11-03 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('cod', 'Cash on Delivery'), ('paybill', 'M-Pesa Paybill'), ('withdraw', 'Withdraw Option')], default='cod', max_length=20)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Order Received'), ('processing', 'Processing'), ('packing', 'Packing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
