# Generated by Django 5.2.7 on 2025-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='is_read',
            new_name='replied',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='email',
            new_name='sender_email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sender_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('draft', 'Draft'), ('archived', 'Archived')], default='inbox', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
