# Generated by Django 5.2.7 on 2025-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_is_read_contactmessage_replied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sender_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
