# Generated by Django 5.2.7 on 2025-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If true, acts as cover image'),
        ),
    ]
