# Generated by Django 5.2.7 on 2025-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, help_text='List of available colors', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition_options',
            field=models.JSONField(blank=True, help_text='["New", "Refurbished"]', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, help_text='List of product features', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(blank=True, help_text='List of storage options', null=True),
        ),
    ]
