# Generated by Django 5.2.7 on 2025-11-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tag_slug_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_options',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('ex_dubai', 'Ex-Dubai')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_gb',
            field=models.IntegerField(blank=True, choices=[(2, '2GB'), (4, '4GB'), (6, '6GB'), (8, '8GB'), (12, '12GB'), (16, '16GB'), (24, '24GB'), (32, '32GB'), (64, '64GB'), (128, '128GB'), (256, '256GB')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_gb',
            field=models.IntegerField(blank=True, choices=[(64, '64GB'), (128, '128GB'), (256, '256GB'), (512, '512GB'), (1024, '1TB'), (2048, '2TB')], null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('ex_dubai', 'Ex-Dubai')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ram',
            field=models.IntegerField(blank=True, choices=[(2, '2GB'), (4, '4GB'), (6, '6GB'), (8, '8GB'), (12, '12GB'), (16, '16GB'), (24, '24GB'), (32, '32GB'), (64, '64GB'), (128, '128GB'), (256, '256GB')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='storage',
            field=models.IntegerField(blank=True, choices=[(64, '64GB'), (128, '128GB'), (256, '256GB'), (512, '512GB'), (1024, '1TB'), (2048, '2TB')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
