# Generated by Django 5.2.7 on 2025-11-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_color_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_options',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GlobalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RAM', 'RAM'), ('STORAGE', 'Storage'), ('COLOR', 'Color')], max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['type', 'value'],
                'unique_together': {('type', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ram_options',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'RAM'}, related_name='ram_products', to='products.globaloption'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'COLOR'}, related_name='color_products', to='products.globaloption'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'STORAGE'}, related_name='storage_products', to='products.globaloption'),
        ),
    ]
