# Generated by Django 5.2.7 on 2025-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
