# Generated by Django 5.2.7 on 2025-10-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops & Computers'), ('tablets', 'Tablets & iPads'), ('accessories', 'Accessories'), ('repairs', 'Repair Services'), ('other', 'Other')], max_length=64)),
                ('product', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
