# Generated by Django 5.2.7 on 2025-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops & Computers'), ('tablets', 'Tablets & iPads'), ('accessories', 'Accessories'), ('repairs', 'Repair Services'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
