# Generated by Django 5.2.7 on 2025-10-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='category',
        ),
    ]
