# Generated by Django 5.2.7 on 2025-11-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='category',
        ),
    ]
